apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodjango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodjango
  template:
    metadata:
      labels:
        app: hellodjango
    spec:
      containers:
      - name: hellodjango
        image: nareshkalakanti/hellodjango:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
